### ISSUE TITLE
Typing - Your typing is backwards

### ISSUE THREAD

**Issue by SVredeveld** [SVredeveld/terrible-ui#8]
Create a new page for a terrible way to type. 

Your typing is backwards. This means that the text that you type goes from right to left.

For example: Writing "Hello" should result in "olleH".

General requirements:
- Create a new page within the correct folder(s).
- make sure you can go back to the main 'Typing' page.
- Keep your code clean and neat. 

Please post a screenshot (or gif) in your pull request.

**Comment by suresh37** [comment]
@SVredeveld  pls assign me this task

**Comment by SVredeveld** [comment]
Yes, go ahead!

**Comment by suresh37** [comment]
@SVredeveld  Please check my PR and merge. Thanks
