### ISSUE TITLE
Phone number - Numpad, but randomised

### ISSUE THREAD

**Issue by SVredeveld** [SVredeveld/terrible-ui#9]
Create a new page for a terrible way to input a phone number. 

Have a numpad, but the numbers are random (and get randomized after every click).

- Add a 'numpad' to your page (clickable numbers).
- After every click, the numbers of the numpad change randomly.
- Make sure you always have the numbers 0 to 9 on the numpad. (no duplicate numbers)
- the chose numbers must be added to the screen, that will _eventually_ show your chose phone number
- A phone number has 10 digits. 
- Add a 'reset' button to reset the chose digits/phone number. 

General requirements:
- Create a new page within the correct folder(s).
- make sure you can go back to the main 'Phone numbers' page.
- Keep your code clean and neat. 

Please post a screenshot (or gif) in your pull request.

**Comment by suryansh-bhatnagar** [comment]
hey @SVredeveld  can i work on this ??

**Comment by SVredeveld** [comment]
Sure, go for it!

**Comment by suryansh-bhatnagar** [comment]
> Sure, go for it!

ok , thank you

**Comment by suryansh-bhatnagar** [comment]
hey @SVredeveld  i have raised a pr #12  could you please review it??
